//! End-to-end reference test: THINDISK.
//!
//! Reproduces the upstream regression case (run_grtrans_test_problems_public.py)
//! from reference/fixtures/thindisk (generated by the Fortran binary at
//! c76cb11). The upstream tolerance is 1e-2 relative on the image.

use grtrans::driver::{trace_ray, SourceParams, TraceOptions};
use grtrans_geodesics::rays::{initialize_geodesic, initialize_pixels};
use grtrans_physics::fluid::{load_fluid_model, FluidArgs};

fn fixture(path: &str) -> Vec<f64> {
    let full = format!(
        "{}/../../reference/fixtures/{path}",
        env!("CARGO_MANIFEST_DIR")
    );
    let bytes = std::fs::read(&full).unwrap_or_else(|_| panic!("missing fixture {full}"));
    bytes
        .chunks_exact(8)
        .map(|c| f64::from_le_bytes(c.try_into().unwrap()))
        .collect()
}

#[test]
fn thindisk_matches_reference() {
    let spin = 0.9;
    let mu0 = 0.26;
    let nx = 100usize;
    let ny = 100usize;
    let nfreq = 25usize;
    let nvals = 4usize;
    let fmin: f64 = 2.41e16;
    let fmax: f64 = 6.31e18;

    let args = initialize_pixels(
        true, 2, mu0, -0.5, spin, 0.01, 1.0, 1.0, 2, -21.0, 21.0, -21.0, 21.0, nx, ny, 1,
    );
    let fargs = FluidArgs {
        mdot: 0.1,
        mbh: 10.0,
        ..Default::default()
    };
    let mut loaded = load_fluid_model("THINDISK", spin, &fargs);

    let freqs: Vec<f64> = (0..nfreq)
        .map(|i| fmin * (((i as f64) * (fmax / fmin).ln() / ((nfreq - 1) as f64)).exp()))
        .collect();
    let opts = TraceOptions {
        ename: "BBPOL".to_string(),
        iname: "lsoda".to_string(),
        nvals,
        freqs,
        ..Default::default()
    };
    let sp = SourceParams {
        mdot: 1.5e15,
        mbh: 10.0,
        ..Default::default()
    };

    let npix = nx * ny;
    let mut ours = vec![0.0f64; npix * nvals * nfreq];
    for i in 0..npix {
        let (ray, status) = initialize_geodesic(&args, i);
        let vals = trace_ray(&mut loaded, &ray, status, &sp, &opts, false);
        for k in 0..nfreq {
            for q in 0..nvals {
                // fixture layout: [pixel][stokes][freq]
                ours[(i * nvals + q) * nfreq + k] = vals[k * nvals + q];
            }
        }
    }

    let reference = fixture("thindisk/ivals.f64.bin");
    assert_eq!(reference.len(), ours.len());
    let num: f64 = ours
        .iter()
        .zip(reference.iter())
        .map(|(a, b)| (a - b).abs())
        .sum();
    let den: f64 = reference.iter().map(|b| b.abs()).sum();
    let err = num / den;
    println!("THINDISK relative error vs upstream reference: {err:e}");
    assert!(err < 1e-2, "THINDISK relative error {err:e} exceeds 1e-2");
}
