#!/usr/bin/env python3
"""Extract the power-law synchrotron interpolation tables from
polsynchemis.f90 and emit a Rust source file.

The Fortran assigns `name=log((/ ... /))` or `name=(/ ... /)` inside
initialize_polsynchpl; we parse those literals (converting Fortran d-exponents)
and emit arrays, preserving which ones are log-transformed at init.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

SRC = Path(sys.argv[1]) if len(sys.argv) > 1 else Path(
    "~/dev/private/grtrans-rs-work/upstream/polsynchemis.f90"
).expanduser()
OUT = Path(sys.argv[2]) if len(sys.argv) > 2 else Path(
    "crates/grtrans-physics/src/polsynch_tables.rs"
)

text = SRC.read_text()

# find the initialize_polsynchpl body
start = text.index("subroutine initialize_polsynchpl")
end = text.index("end subroutine initialize_polsynchpl")
body = text[start:end]

# collapse whitespace/newlines for parsing
flat = " ".join(body.split())

assignments = {}
# pattern: name=log((/ ... /)) or name=(/ ... /)
for m in re.finditer(r"(\w+)\s*=\s*(log)?\(\(/(.*?)/\)\)", flat):
    name, is_log, data = m.group(1), m.group(2), m.group(3)
    nums = re.findall(r"[0-9]+\.?[0-9]*(?:[dD][+-]?[0-9]+)?", data)
    vals = [float(n.lower().replace("d", "e")) for n in nums]
    assignments[name] = (is_log is not None, vals)
    print(f"{name}: {len(vals)} values, log={is_log is not None}")

expected = {
    "gxvals": 181, "gyvals": 181 * 3,
    "xvals": 81, "yavals": 81 * 3, "ypvals": 81 * 3, "yvvals": 81 * 3,
    "yapvals": 81 * 3, "yavvals": 81 * 3,
}
for name, n in expected.items():
    if name not in assignments:
        print(f"WARNING: {name} not found")
    elif len(assignments[name][1]) != n:
        print(f"WARNING: {name} has {len(assignments[name][1])} values, expected {n}")

lines = []
lines.append("//! Generated by scripts/extract_polsynch_tables.py from")
lines.append("//! polsynchemis.f90 (jadexter/grtrans @ c76cb11). Do not edit.")
lines.append("")
lines.append("/// Raw table values (before the upstream log transform).")
lines.append("#[derive(Debug)]")
lines.append("pub struct PolsynchTables {")
for name in expected:
    is_log, vals = assignments[name]
    n = len(vals)
    lines.append(f"    /// upstream `{name}` (log={is_log})")
    lines.append(f"    pub {name}: [f64; {n}],")
lines.append("}")
lines.append("")
lines.append("/// Table data exactly as written in the Fortran source.")
lines.append("pub static TABLES: PolsynchTables = PolsynchTables {")
for name in expected:
    is_log, vals = assignments[name]
    lines.append(f"    {name}: [")
    for i in range(0, len(vals), 4):
        chunk = ", ".join(f"{v!r}" for v in vals[i : i + 4])
        lines.append(f"        {chunk},")
    lines.append("    ],")
lines.append("};")
lines.append("")

OUT.parent.mkdir(parents=True, exist_ok=True)
OUT.write_text("\n".join(lines) + "\n")
print(f"wrote {OUT}")
