# compiler choice
USEINTEL=0
USEGNU=1
DEBUG=0
XEONPHI=0
PROFILE=0
CFITSIODIR=/opt/homebrew/lib
GRTRANSDIR=/Users/yonidavidson/dev/private/grtrans-rs-work/upstream
FFLAGS=-std=legacy -fallow-argument-mismatch
